import "../globals.css";
import Header from "../header";
import NavBar from "../nav-bar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="bg-noise-bg" lang="en">
      <body className="bg-gradient-to-b from-[#001B26] to-slate-900 opacity-95 min-h-screen">
        <NavBar />
        <Header />
        <div>{children}</div>
      </body>
    </html>
  );
}
