import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="bg-noise-bg" lang="en">
      <body className="bg-gradient-to-b from-sky-950 to-slate-900 opacity-95 min-h-screen">
        {children}
      </body>
    </html>
  );
}
